/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import ServidorBD.Sql;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ivimar
 */
public class VistaVehiculos extends javax.swing.JFrame {
    JTable tabla;
    ResultSet rs;

    /**
     * Creates new form VistaVehiculos
     */
    public VistaVehiculos() {
        initComponents();
        
        DefaultTableModel dfm = new DefaultTableModel();
        tabla = this.jtVistaVehiculos;
        tabla.setModel(dfm);
        //creamos tantas columnas como tenga nuesta tabla
        dfm.setColumnIdentifiers(new Object[]{"ID Vehiculo", "Marca", "Modelo", "Matricula", "Kilometros Alta","Fecaha Alta",
            "Fecha Baja", "ID Conductor", "ID Empresa", "Kilometros Actuales"
        });
        
        Sql sql = new Sql();
        rs = sql.VerTodosVehiculos();
        
        try {         
            //leemos todo el rs hasta que no haya mas resultados en nuestra tabla
            while(rs.next()){
            dfm.addRow(new Object[]{rs.getInt("idvehiculo"),rs.getString("marca"), rs.getString("modelo"),
                rs.getString("matricula"), rs.getFloat("kilometros_alta"), rs.getDate("Fecha_alta"),
                rs.getDate("Fecha_baja"),
                rs.getInt("conductorid"),rs.getInt("empresaid"),rs.getFloat("kilometros_actuales")});
            
            }
        } catch (SQLException ex) {
            Logger.getLogger(VistaVehiculos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jsVistaVehiculos = new javax.swing.JScrollPane();
        jtVistaVehiculos = new javax.swing.JTable();
        btnVistaVehiculo_volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtVistaVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "colum1", "colum2", "colum3"
            }
        ));
        jsVistaVehiculos.setViewportView(jtVistaVehiculos);

        btnVistaVehiculo_volver.setText("Volver");
        btnVistaVehiculo_volver.setActionCommand("");
        btnVistaVehiculo_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVistaVehiculo_volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jsVistaVehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVistaVehiculo_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jsVistaVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVistaVehiculo_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVistaVehiculo_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVistaVehiculo_volverActionPerformed
        try {
            this.setVisible(false);
        } catch (Throwable ex) {
            Logger.getLogger(VistaInsertarVehiculos.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnVistaVehiculo_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaVehiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVistaVehiculo_volver;
    private javax.swing.JScrollPane jsVistaVehiculos;
    private javax.swing.JTable jtVistaVehiculos;
    // End of variables declaration//GEN-END:variables
}
